### PR TITLE
fix args name mismatch

### PR DESCRIPTION
**Pull request by vukasin**
Addresses https://github.com/worldbank/REaLTabFormer/issues/90
Passing the arguments by name to ensure proper assignment in the `transformers` constructor.

### CODE REVIEW

**Comment by avsolatorio** [comment]
Hello @vukasin , Thanks so much for this PR! Could you please update the package's dependency to `transformers >= v4.46.0`?

Otherwise, this will cause a breaking change for transformers lower than that version; see: https://github.com/huggingface/transformers/blob/c2820c94916e34baf4486accae74760972183a2f/src/transformers/trainer.py#L331

I also suggest removing the `devcontainer` file currently included in the committed files.

**Comment by vukasin** [comment]
@avsolatorio. I've made the changes you suggested

**Comment by avsolatorio** [comment]
Thanks, @vukasin ! Merged! :)

**Comment by avsolatorio** [comment]
Closes #90

**Pull request merged**
